declare module '@soccerwatch/discovery'
declare module 'react-router-dom'
declare module 'react-native-nav'
declare module 'react-object-list'
declare module 'react-object-list/icons'
declare module 'lodash'
declare module 'react-color'
